project_id = "pxwebybxfqywvnoenprs"

[functions.load-apmc-data]
verify_jwt = false

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[functions.weather]
verify_jwt = false

[functions.mandi-prices]
verify_jwt = false

[functions.ai-advisor]
verify_jwt = false

[functions.soil-detector]
verify_jwt = false

[functions.crop-disease-detector]
verify_jwt = false

[functions.equipment]
verify_jwt = false
